<!DOCTYPE html>
<html lang="en">
<?php session_start(); ?>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>post</title>
    <link rel="stylesheet" href="../CSS/style.css">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

   

</head>
<body>
    <!-- navbar -->
    <!-- <?php
        // $selected = "post2";
        // $current_id = ' class="active"';
        // include "../nav.php";
    ?> -->
    <nav>
       <a href="../index.php" class="logo"><h1>SKILL SHARP</h1></a>
        <div class="navigation">
            <ul class="ul">
                <i id="close-btn" class="fas fa-times"></i>
                <li><a  href="../index.php">Home</a></li>
                <li><a  href="../about.php">About</a></li>
                <li><a class="active" href="../blog.php">Blog</a></li>
                <li><a href="../course.php">courses</a></li>
                <li><a href="../contact.php">Contact</a></li>
            </ul>
          <img id="menu-btn" src="../../images/menu.png" alt=""  >
        </div>
    </nav>
    

    
    <section id="blog-container">
        <div class="blogs blogpost">
            <div class="post">
                <img src="../images/blog2.jpg" alt="">
                <h3>Learn Javascript</h3>
                <p>JavaScript is a dynamic computer programming language. It is lightweight and most commonly used as a part of web pages, whose implementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities.
                    <br><br>
                    JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.
                    <br><br>
                    The ECMA-262 Specification defined a standard version of the core JavaScript language.

                    <ul>
                        <li>JavaScript is a lightweight, interpreted programming language.</li>
                        <li>Designed for creating network-centric applications.</li>
                        <li> Complementary to and   integrated with Java.</li>
                        <li> Complementary to and integrated with HTML.</li>
                        <li> Open and cross-platform</li>
                    </ul>
                    <h3>Client-Side JavaScript</h3>
                    Client-side JavaScript is the most common form of the language. The script should be included in or referenced by an HTML document for the code to be interpreted by the browser.
                    <br><br>
                    It means that a web page need not be a static HTML, but can include programs that interact with the user, control the browser, and dynamically create HTML content.
                    <br><br>
                    The JavaScript client-side mechanism provides many advantages over traditional CGI server-side scripts. For example, you might use JavaScript to check if the user has entered a valid e-mail address in a form field.
                    <br><br>
                    The JavaScript code is executed when the user submits the form, and only if all the entries are valid, they would be submitted to the Web Server.
                    <br><br>
                    JavaScript can be used to trap user-initiated events such as button clicks, link navigation, and other actions that the user initiates explicitly or implicitly.
                    <br><br>
                    <h3>Advantages of JavaScript</h3>
                    The merits of using JavaScript are −
                    <br><br>
                    <ul>
                    <li> Less server interaction − You can validate user input before sending the page off to the server. This saves server traffic, which means less load on your server.</li>
                    
                    <li> Immediate feedback to the visitors − They don't have to wait for a page reload to see if they have forgotten to enter something.</li>
                    
                    <li> Increased interactivity − You can create interfaces that react when the user hovers over them with a mouse or activates them via the keyboard.</li>
                    
                    <li> Richer interfaces − You can use JavaScript to include such items as drag-and-drop components and sliders to give a Rich Interface to your site visitors.</li>
                    </ul>
                    <br><br>
                   <h3>Limitations of JavaScript</h3>
                   
                    We cannot treat JavaScript as a full-fledged programming language. It lacks the following important features −
                    <br><br>
                    <ul> 
                        <li> Client-side JavaScript does not allow the reading or writing of files. This has been kept for security reason.</li>
                    
                        <li> JavaScript cannot be used for networking applications because there is no such support available.</li>
                    
                        <li> JavaScript doesn't have any multi-threading or multiprocessor capabilities.</li>
                    </ul>
                    Once again, JavaScript is a lightweight, interpreted programming language that allows you to build interactivity into otherwise static HTML pages.
                    
                    <h3>JavaScript Development Tools</h3>
                    One of major strengths of JavaScript is that it does not require expensive development tools. You can start with a simple text editor such as Notepad. Since it is an interpreted language inside the context of a web browser, you don't even need to buy a compiler.
                    <br><br>
                    To make our life simpler, various vendors have come up with very nice JavaScript editing tools. Some of them are listed here −
                    <ul>
                        <li> Microsoft FrontPage − Microsoft has developed a popular HTML editor called FrontPage. FrontPage also provides web developers with a number of JavaScript tools to assist in the creation of interactive websites.</li>
                    
                        <li> Macromedia Dreamweaver MX − Macromedia Dreamweaver MX is a very popular HTML and JavaScript editor in the professional web development crowd. It provides several handy prebuilt JavaScript components, integrates well with databases, and conforms to new standards such as XHTML and XML.</li>
                    
                        <li> Macromedia HomeSite 5 − HomeSite 5 is a well-liked HTML and JavaScript editor from Macromedia that can be used to manage personal websites effectively.</li>
                </ul> </p>
                    
            </div>
        </div>
    </section>

   

   
    <!-- Footer -->

    <?php
    include "../footer.php";
    ?>

</body>
</html>